### ISSUE TITLE
As a user, I faced multiple errors when trying to run everything on my own file

### ISSUE THREAD

**Issue by Adafede** [SoseiHeptares/smizip#3]
Adressing the following might help:

- [x] Add an example smi file (See #4 )
- [x] Change the default list in `find_best_ngrams.py` or make it more explicit and also document it in the `README`. (See #5 )
- [ ] Allow for more multigrams not being found in lookups. (See #6 )
- [x] Allow for shorter smi files. Make corresponding parameters work with any lengths. (See #7 )

**Comment by baoilleach** [comment]
Three out of the four of these are closed, so I'm going to close this one just to tidy up as it doesn't add anything.
